"""Feature extraction modules."""

from src.features import cwt, envelope, frequency_domain, fusion, stft, temporal, time_domain
from src.features.fusion import (
    ExtractionMode,
    FeatureExtractor,
    FeatureInfo,
    NUM_ALL_FEATURES,
    NUM_FREQ_FEATURES,
    NUM_TIME_FEATURES,
    extract_all_features,
    extract_all_features_dict,
    get_all_feature_names,
    get_feature_groups,
)
from src.features.time_domain import (
    CHANNEL_FEATURES as TIME_DOMAIN_FEATURES,
    NUM_FEATURES_PER_CHANNEL as NUM_TIME_FEATURES_PER_CHANNEL,
    extract_channel_features as extract_time_channel_features,
    extract_cross_correlation,
    extract_features as extract_time_features,
    extract_features_dict as extract_time_features_dict,
    get_feature_names as get_time_feature_names,
)
from src.features.frequency_domain import (
    SPECTRAL_FEATURES,
    CHARACTERISTIC_FEATURES,
    NUM_SPECTRAL_FEATURES,
    NUM_CHARACTERISTIC_FEATURES,
    calculate_bearing_frequencies,
    get_characteristic_frequencies_for_condition,
    extract_features as extract_freq_features,
    extract_features_dict as extract_freq_features_dict,
    get_feature_names as get_freq_feature_names,
)
from src.features.stft import (
    STFTConfig,
    NormalizationMode,
    extract_spectrogram,
    generate_mel_spectrogram,
    generate_spectrogram_dual_channel,
    generate_linear_spectrogram,
    create_mel_filterbank,
    compute_stft,
    get_default_config as get_default_stft_config,
)
from src.features.envelope import (
    EnvelopeConfig,
    FilterType,
    ENVELOPE_FEATURE_NAMES,
    NUM_ENVELOPE_FEATURES,
    get_default_config as get_default_envelope_config,
    design_bandpass_filter,
    apply_bandpass_filter,
    compute_envelope,
    compute_envelope_spectrum,
    extract_envelope_statistics,
    extract_envelope_features,
    extract_envelope_features_dual_channel,
    extract_envelope_features_dict,
    get_envelope_feature_names,
    get_dual_channel_feature_names as get_envelope_dual_channel_feature_names,
    detect_fault_signatures,
    analyze_bearing_health,
)
from src.features.cwt import (
    CWTConfig,
    NormalizationMode as CWTNormalizationMode,
    extract_scalogram,
    generate_scalogram,
    generate_scalogram_dual_channel,
    generate_scalograms_batched,
    compute_cwt,
    get_default_config as get_default_cwt_config,
    get_scale_frequencies,
    estimate_memory_usage as estimate_cwt_memory_usage,
)
from src.features.temporal import (
    TEMPORAL_BASE_FEATURES,
    DEFAULT_LAGS,
    DEFAULT_ROLLING_WINDOWS,
    enrich_temporal_features,
    get_temporal_feature_names,
)

__all__ = [
    # Submodules
    "time_domain",
    "frequency_domain",
    "fusion",
    "stft",
    "envelope",
    "cwt",
    "temporal",
    # Temporal enrichment exports
    "TEMPORAL_BASE_FEATURES",
    "DEFAULT_LAGS",
    "DEFAULT_ROLLING_WINDOWS",
    "enrich_temporal_features",
    "get_temporal_feature_names",
    # Fusion exports (unified interface)
    "ExtractionMode",
    "FeatureExtractor",
    "FeatureInfo",
    "NUM_ALL_FEATURES",
    "NUM_FREQ_FEATURES",
    "NUM_TIME_FEATURES",
    "extract_all_features",
    "extract_all_features_dict",
    "get_all_feature_names",
    "get_feature_groups",
    # Time-domain exports
    "TIME_DOMAIN_FEATURES",
    "NUM_TIME_FEATURES_PER_CHANNEL",
    "extract_time_channel_features",
    "extract_cross_correlation",
    "extract_time_features",
    "extract_time_features_dict",
    "get_time_feature_names",
    # Frequency-domain exports
    "SPECTRAL_FEATURES",
    "CHARACTERISTIC_FEATURES",
    "NUM_SPECTRAL_FEATURES",
    "NUM_CHARACTERISTIC_FEATURES",
    "calculate_bearing_frequencies",
    "get_characteristic_frequencies_for_condition",
    "extract_freq_features",
    "extract_freq_features_dict",
    "get_freq_feature_names",
    # STFT/Spectrogram exports
    "STFTConfig",
    "NormalizationMode",
    "extract_spectrogram",
    "generate_mel_spectrogram",
    "generate_spectrogram_dual_channel",
    "generate_linear_spectrogram",
    "create_mel_filterbank",
    "compute_stft",
    "get_default_stft_config",
    # Envelope analysis exports
    "EnvelopeConfig",
    "FilterType",
    "ENVELOPE_FEATURE_NAMES",
    "NUM_ENVELOPE_FEATURES",
    "get_default_envelope_config",
    "design_bandpass_filter",
    "apply_bandpass_filter",
    "compute_envelope",
    "compute_envelope_spectrum",
    "extract_envelope_statistics",
    "extract_envelope_features",
    "extract_envelope_features_dual_channel",
    "extract_envelope_features_dict",
    "get_envelope_feature_names",
    "get_envelope_dual_channel_feature_names",
    "detect_fault_signatures",
    "analyze_bearing_health",
    # CWT/Scalogram exports
    "CWTConfig",
    "CWTNormalizationMode",
    "extract_scalogram",
    "generate_scalogram",
    "generate_scalogram_dual_channel",
    "generate_scalograms_batched",
    "compute_cwt",
    "get_default_cwt_config",
    "get_scale_frequencies",
    "estimate_cwt_memory_usage",
]
